language: python
python:
- 3.7
install:
- pip install --requirement requirements.txt
script:
- pip install .[ase]
- sphinx-apidoc --force -o docs/source/doc/ mbgdml ./tests/
- sphinx-build -nT docs/source/ docs/html/
- touch ./docs/html/.nojekyll
- pytest --cov=./
after_success:
- codecov
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/html/
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master