language: python
python:
  - 3.7

install:
  - pip install --requirement requirements.txt
  - pip install codecov pytest-cov
script:
  - pip install sphinx_rtd_theme
  - sphinx-build -nT docs/source/ docs/html/
  - sphinx-apidoc -o docs/source/doc mbgdml
  - pytest --cov=./

# Push the results back to codecov
after_success:
  - codecov
  - ./push.sh

env:
  global:
  - secure:CEMYH8OCmhWwbLC4JKIX+UUtWLgVH9Tokzpm+qBxAgD/qHGFgebSOGSAsxHgvXo3xNVjjWCIjySQDaObh51X/jpGFfhiovPke6GZ15b7BC6yL0AYJsM4GbHWdk39wwzFrA6EMIf1wIIju2paB38WPQstJuPdumCAQb9KVZvX+rotdEVjexkim+/3O0zldExg80Fg89AYwLfvwLHgCaP5UBWNMGmIT6FQuF4YBm+55x4D6RQ53WehfbxIfMP4JPBjcoXSFytobmuid7PyaVcBMLju6dfrGS0vHXTc/374VK7K+6BtnP+ksGJsrtm/5X0dWHCV35ldafdA7IT5j2Q7by+HdUNjlZSQJoS9n58xWNT3JWPFPG7Lbt4vcAkQg2/Nm8I8FvP7ejMl0rIR1OZti9/sP7Oy/Mc87quEGkl39EiviyBjrSNNxejFEHG5sGq+ALlM00UboKYXJcL3ovHiel7sLjYm8mGRBE3nRU5dBMMRFiAUf0yZcOaKm3etYMAboiiw/5Z5xs/cNClLDjG+OpoScCJjMB6tZLF7HGNeqFyo8D3yY3kP9fAlq/VxQMXM/XmJUfqxoNZyZekyPX31WLouDYeMeKUwbYHHfErXNOSbzhzSfYDgX3IVXKoA0NHasyak9xBMuUqLA8mgQmMw5mOmbW+pB3gLBhlzlfyLIsQ= "QKGPoUyKqCPwpA3kvZXMFToMghFgNfKYpKh96L//t682NVdBNSt9ZnF+2oKVSABrbHfmdn3kuLe2CFokK2EckhZeUQHOgrS4XcNod+VW+yHLFNb6++A6gCPkOp2nOTkyLar9xJCwHE0+UVMmkP2T52HkDpu/1H0K+SkCussrnEhI2faAUS+JY1RukWmd5PBL1EHtqrfMRP5ZbAB3mgHY1xTyKjS6mawmxJ/TNyL35Wb9T4dR+I61r+OgToI9zO6Bzma10GHOUGWE0GI722JmyQIz18reJZjkKRkZwgcR0DkvLXtylur46TI/nMSTSCTRH2wlRvda0eVtLf7dh1zDunjNkZatOhCjqoZrK0Lnom2f0OOcOI92PZJvLQjKx3oeWnA4ZdT8OQe531T/Jh7W7SHPDTCbI4tnrqKC54Mt9kXNlTUdDIMbBtLyhgoW5Hl9ZUh/ovDQ5fKC3OreuIrwcDnjcQsvTvj+Uu/NfUfxT9ZBCbkBxYs1e82yiy+b8O9HcEWNAt6CHykzDeF4O/4J7GpYun/zJj6qNy7yJP+LFPdULZ0nNu8NlkhIXC92t+R8Du34KtDxEr+ogL3FbzmFc39tfbmOXR5AaQeA2UcWJzdduhRxIft5LH8Pz0c1fyU7y/lNDFWJQk7yaIj4t1/gQ+21T1hrYl4Mt0Ga/jalcZE="
  - CODECOV_TOKEN="b0254cb7-5006-4c97-9e7a-880fe61c3bbf"
