language: python
python:
  - 3.7

install:
  - pip install --requirement requirements.txt
script:
  - pip install .[ase]
  - sphinx-apidoc --force -o docs/source/doc/ mbgdml ./tests/
  - sphinx-build -nT docs/source/ docs/html/
  - pytest --cov=./

after_success:
  - codecov

deploy:
  provider: pages
  local_dir: ./docs/html/
  repo: keithgroup/mbGDML
  target_branch: gh-pages
  keep_history: true
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master

env:
  global:
  - secure: LQOIv7DDCixS/eoTLuStEUC55uinxsxin8Aw48MUm0cgI/JFojP2cFNQ1QUvNqRgafCl2VPLn6JyJZt/ESF0bu8SNnhAEe6Ld78i7IrgOINkNdsESlgxmDgDL8g1wSkE4MUN9MV5k9WGr3q1Biu5/47ITTwOcLNjY7oy/Lkjv52cDvcQ0znMZicNLbej2ugNBA90H7LWiQsQ8JkUhkNqUN5PB/ruLOe9Nw4oo42KiXmtazeRWMrFCzTsH2PL9Tx7tmh1X+AZPLqYShF0IASI3//xG4BpNKIrtYai+Z9t3lYjy6XNRj2ggHuZcrmWJK5jc0bh/0ojeopwh4jEC9qsD8wrXpUJdsSDZ8EFNgm3Pi7MtRLCyFN8xN19XW52x6V697M13iYWcaSzujeGGVYbPsW0DQD7444v894cLlzCDlcWynqbiW6lOZZwNPCXcI5cYEbv5CM0+2iTSnGIq45rI+BxvZZttGNFFpdNO+g9bWmTMPkhA6tAZh5p/41EcLYFnCe7wXJMtIK8fCPVX0vP/epy+NQEewMSvWZmnnDwAtyvG/xDeVZgynCqlKJH/fDgyBidXVqu4xh7iWB5/kMTOZzKSMXDZ2OlPlR2HQmgLUOj9n/ScCtnmqc479Uurnt0OaRstOpxgJOgHf6GNgydybAX68r8EIpAnnfGEiQhyeA=
